services:

    # Apache
    apache:
        image: php:8.2-apache
        container_name: lamp_apache
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./www:/var/www/html
        depends_on:
            - db
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - mynetwork

    # MySQL
    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        container_name: lamp_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: lamp
            MYSQL_USER: lamp
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - mynetwork

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lamp_phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        depends_on:
            - db
        networks:
            - mynetwork

    # MailHog
    mailhog:
        image: mailhog/mailhog
        container_name: lamp_mailhog
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge

volumes:
    db_data: